version: '3.1'

services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: root
    volumes:
      - ./docker-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: toor
    ports:
      - "5050:80"
